# Generated by Django 2.0.5 on 2018-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Sportsmens',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Порядковый номер атлета')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО атлета')),
                ('city', models.CharField(max_length=100, verbose_name='Город, спортивный клуб')),
                ('trener', models.CharField(max_length=100, verbose_name='ФИО тренера')),
                ('category', models.ManyToManyField(to='sportsmens.Categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Атлет',
                'verbose_name_plural': 'Атлеты',
            },
        ),
    ]
