# Generated by Django 2.0.5 on 2018-06-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsmens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Место')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sportsmens',
            options={'ordering': ['id'], 'verbose_name': 'Athlete', 'verbose_name_plural': 'Athletes'},
        ),
        migrations.AddField(
            model_name='rating',
            name='sportsmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmens.Sportsmens', verbose_name='Оценивающий спортсмен'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценивающий судья'),
        ),
    ]
