# Generated by Django 2.0.5 on 2018-06-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmens', '0002_auto_20180601_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='sportsmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmens.Sportsmens', verbose_name='Оцениваемый спортсмен'),
        ),
    ]
