# Generated by Django 2.0.5 on 2018-06-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsmens', '0003_auto_20180601_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsmens_and_category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Айди связи спортсмена и категории')),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmens.Categories', verbose_name='Айди категории')),
            ],
            options={
                'db_table': 'sportsmens_and_category',
            },
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='sportsmens_and_category',
            name='sportsmens_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsmens.Sportsmens', verbose_name='Айди спортсмена'),
        ),
    ]
